### ISSUE TITLE
Generated converters from submodules aren't recognized in KSP processing

### ISSUE THREAD

**Issue by Xeonkryptos** [mcarleio/konvert#78]
Based on the response from issue #19 

> Konvert registers all @KonverTo, @KonvertFrom and @Konvert/@Konverter functions as TypeConverters during KSP run. It even works between multiple modules, e.g. when you have a module A where you define the MyCustomConverter and a module B which depends on module A where you have a mapping from String->Currency, then Konvert knows the MyCustomConverter and will use it.

it should be possible to define a converter in one module and it's going to be used in another module if a dependency exists and the types matches. Sadly, for me it doesn't work.

Make a simple gradle kotlin project with

module A containing
```kotlin
data class Dummy1(val id: Long)

@KonvertTo(Dummy2::class, mappings = [Mapping(source = "id", target = "userId")])
data class Dummy2(val userId: UserId)

@Konverter
interface DummyMapper {

    @Konvert(mappings = [Mapping(source = "id", target = "userId", enable = [""])])
    fun toDummy2(dummy1: Dummy1): Dummy2
}
```

The corresponding gradle.kts file of module A looks as following:

```kotlin
plugins {
    kotlin("jvm") version "1.9.23"
    id("com.google.devtools.ksp") version "1.9.23-1.0.20"
}

group = "com.example"

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":module-2"))
    implementation("io.mcarle:konvert-api:3.2.1")
    ksp("io.mcarle:konvert:3.2.1")
}

kotlin {
    jvmToolchain(21)
}
```

module B containing
```kotlin
@JvmInline
value class UserId(val value: Long)

@Konverter
interface UserIdMapper {
    fun toUserId(value: Long): UserId = UserId(value)
}
```

The gradle.kts of module B is

```kotlin
plugins {
    kotlin("jvm") version "1.9.23"
    id("com.google.devtools.ksp") version "1.9.23-1.0.20"
}

group = "com.example"

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.mcarle:konvert-api:3.2.1")
    ksp("io.mcarle:konvert:3.2.1")
}

kotlin {
    jvmToolchain(21)
}
```

Module B is compiling correctly and you can see the generated mapper. When compiling Module A KSP crashes with

```
[ksp] io.mcarle.konvert.processor.exceptions.NoMatchingTypeConverterException: No converter for dummy1.id -> userId: Long -> UserId
	at io.mcarle.konvert.processor.codegen.MappingCodeGenerator.throwException(MappingCodeGenerator.kt:257)
	at io.mcarle.konvert.processor.codegen.MappingCodeGenerator.access$throwException(MappingCodeGenerator.kt:23)
	at io.mcarle.konvert.processor.codegen.MappingCodeGenerator$convertValue$1.invoke(MappingCodeGenerator.kt:239)
	at io.mcarle.konvert.processor.codegen.MappingCodeGenerator$convertValue$1.invoke(MappingCodeGenerator.kt:236)
	at io.mcarle.konvert.converter.api.TypeConverterRegistry.withAdditionallyEnabledConverters(TypeConverterRegistry.kt:47)
	at io.mcarle.konvert.processor.codegen.MappingCodeGenerator.convertValue(MappingCodeGenerator.kt:236)
	at io.mcarle.konvert.processor.codegen.MappingCodeGenerator.constructorParamsCode(MappingCodeGenerator.kt:118)
	at io.mcarle.konvert.processor.codegen.MappingCodeGenerator.constructorCode(MappingCodeGenerator.kt:80)
	at io.mcarle.konvert.processor.codegen.MappingCodeGenerator.generateMappingCode(MappingCodeGenerator.kt:35)
	at io.mcarle.konvert.processor.codegen.CodeGenerator.generateCode(CodeGenerator.kt:81)
	at io.mcarle.konvert.processor.konvert.KonverterCodeGenerator.generateMappingCode(KonverterCodeGenerator.kt:110)
	at io.mcarle.konvert.processor.konvert.KonverterCodeGenerator.access$generateMappingCode(KonverterCodeGenerator.kt:22)
	at io.mcarle.konvert.processor.konvert.KonverterCodeGenerator$generate$1$1$1$1.invoke(KonverterCodeGenerator.kt:75)
	at io.mcarle.konvert.processor.konvert.KonverterCodeGenerator$generate$1$1$1$1.invoke(KonverterCodeGenerator.kt:40)
	at io.mcarle.konvert.converter.api.config.ConfigurationKt.withIsolatedConfiguration(Configuration.kt:54)
	at io.mcarle.konvert.processor.konvert.KonverterCodeGenerator$generate$1.invoke(KonverterCodeGenerator.kt:40)
	at io.mcarle.konvert.processor.konvert.KonverterCodeGenerator$generate$1.invoke(KonverterCodeGenerator.kt:28)
	at io.mcarle.konvert.converter.api.config.ConfigurationKt.withIsolatedConfiguration(Configuration.kt:54)
	at io.mcarle.konvert.processor.konvert.KonverterCodeGenerator.generate(KonverterCodeGenerator.kt:28)
	at io.mcarle.konvert.processor.KonvertProcessor.generateMappingCode(KonvertProcessor.kt:71)
	at io.mcarle.konvert.processor.KonvertProcessor.access$generateMappingCode(KonvertProcessor.kt:24)
	at io.mcarle.konvert.processor.KonvertProcessor$process$1.invoke(KonvertProcessor.kt:42)
	at io.mcarle.konvert.processor.KonvertProcessor$process$1.invoke(KonvertProcessor.kt:33)
	at io.mcarle.konvert.converter.api.config.ConfigurationKt.withIsolatedConfiguration(Configuration.kt:42)
	at io.mcarle.konvert.processor.KonvertProcessor.process(KonvertProcessor.kt:33)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

If you now move the UserIdMapper definition from Module B into Module A where it is required, no crash occurs. The compilation works fine and the mapping works.

If you don't have the UserIdMapper in this case in your current module where it is required, then it doesn't generate the mapping as usually expected. It doesn't work with KonvertTo or KonvertFrom either.

Multi module support doesn't seem to work, at least in gradle and I don't want to copy a mapper into different modules to make them compile. I'd like to be able to place it into a module that is used by others and has the generated converters being recognized at KSP processing time.

**Comment by mcarleio** [comment]
Thank you for raising this, I need to check what might have changed since then, because I am certain this was working as expected when I implemented it :confused: 

For now you can probably work around, by letting `DummyMapper` extend from `UserIdMapper`.

---

I have an idea that will improve this, but it would still not work as I would expected how it did work in the past (and how you also expected it to work)

What do you think about a solution like this (gradle.kts of module A)
```
    implementation(project(":module-2"))
    implementation("io.mcarle:konvert-api:3.2.1")

    ksp(project(":module-2"))  // <- add module-2 as KSP dependency, so that the processor can access the resources (META-INF/konvert/...)
    ksp("io.mcarle:konvert:3.2.1")
```

I would need to change some minor stuff to get that working, but then it could work.
I hope that the final solution nevertheless can be without the extra ksp line, but I have to dig deeper into that.

**Comment by Xeonkryptos** [comment]
Right, extension is a possibility too, to work around this issue. That didn't came to mind.

Don't know about the ksp dependency. If I have to choose between the KSP dependency and the extension, I'd choose the extension over it.

It isn't an urgent issue for me. Personally, I don't need the KSP workaround in a bugfix release just to have it working that way. Take your time looking into it and fixing it. I can work perfectly fine with the extension workaround.

**Comment by sato9818** [comment]
We have encountered the same issue. I would like to know if there is any update on this issue?

**Comment by mcarleio** [comment]
Currently not. The original solution with a META-INF file stopped working at some point and I did not (yet) found a good way to pass information from one module as input to the KSP run of another.

I am open for ideas!

**Comment by mcarleio** [comment]
implemented in version 4
